/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.vista;

/**
 *
 * @author user
 */
public class VistaPersonal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPersonal
     */
    public VistaPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Personal = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Apellido = new javax.swing.JLabel();
        txt_Apellido = new javax.swing.JTextField();
        lbl_Ocupacion = new javax.swing.JLabel();
        txt_Ocupacion = new javax.swing.JTextField();
        lbl_Salario = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        lbl_Correo = new javax.swing.JLabel();
        txt_Salario = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Personal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_Personal.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Personal.setText("PERSONAL");
        lbl_Personal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_Nombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Nombre.setText("Nombre:");

        lbl_Apellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Apellido.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Apellido.setText("Apellido:");

        lbl_Ocupacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Ocupacion.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Ocupacion.setText("Ocupacion:");

        lbl_Salario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Salario.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Salario.setText("Salario:");

        lbl_Telefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Telefono.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Telefono.setText("Telefono:");

        lbl_Correo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Correo.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Correo.setText("Correo:");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Apellido)
                                .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Nombre)
                                .addComponent(lbl_Ocupacion)
                                .addComponent(txt_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Salario)
                                .addComponent(txt_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Telefono)
                                .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Correo)
                                .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Personal)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_Personal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbl_Apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Ocupacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lbl_Personal.getAccessibleContext().setAccessibleName("lbl_Personal");
        lbl_Personal.getAccessibleContext().setAccessibleParent(lbl_Personal);
        txt_Nombre.getAccessibleContext().setAccessibleName("txt_Nombre");
        txt_Nombre.getAccessibleContext().setAccessibleParent(txt_Nombre);
        lbl_Nombre.getAccessibleContext().setAccessibleName("lbl_Nombre");
        lbl_Nombre.getAccessibleContext().setAccessibleDescription("");
        lbl_Nombre.getAccessibleContext().setAccessibleParent(lbl_Nombre);
        lbl_Apellido.getAccessibleContext().setAccessibleName("lbl_Apellido");
        lbl_Apellido.getAccessibleContext().setAccessibleParent(lbl_Apellido);
        txt_Apellido.getAccessibleContext().setAccessibleName("txt_Apellido");
        txt_Apellido.getAccessibleContext().setAccessibleParent(txt_Apellido);
        lbl_Ocupacion.getAccessibleContext().setAccessibleName("lbl_Ocupacion");
        lbl_Ocupacion.getAccessibleContext().setAccessibleParent(lbl_Ocupacion);
        txt_Ocupacion.getAccessibleContext().setAccessibleName("txt_Ocupacion");
        txt_Ocupacion.getAccessibleContext().setAccessibleParent(txt_Ocupacion);
        lbl_Salario.getAccessibleContext().setAccessibleName("lbl_Salario");
        lbl_Salario.getAccessibleContext().setAccessibleParent(lbl_Salario);
        lbl_Telefono.getAccessibleContext().setAccessibleName("lbl_Telefono");
        lbl_Telefono.getAccessibleContext().setAccessibleParent(lbl_Telefono);
        lbl_Correo.getAccessibleContext().setAccessibleName("lbl_Correo");
        lbl_Correo.getAccessibleContext().setAccessibleParent(lbl_Correo);
        txt_Salario.getAccessibleContext().setAccessibleName("txt_Salario");
        txt_Salario.getAccessibleContext().setAccessibleParent(txt_Salario);
        txt_Telefono.getAccessibleContext().setAccessibleName("txt_Telefono");
        txt_Telefono.getAccessibleContext().setAccessibleDescription("");
        txt_Telefono.getAccessibleContext().setAccessibleParent(txt_Telefono);
        txt_Correo.getAccessibleContext().setAccessibleName("txt_Correo");
        txt_Correo.getAccessibleContext().setAccessibleParent(txt_Correo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Apellido;
    public javax.swing.JLabel lbl_Correo;
    private javax.swing.JLabel lbl_Nombre;
    public javax.swing.JLabel lbl_Ocupacion;
    private javax.swing.JLabel lbl_Personal;
    public javax.swing.JLabel lbl_Salario;
    public javax.swing.JLabel lbl_Telefono;
    public javax.swing.JTextField txt_Apellido;
    public javax.swing.JTextField txt_Correo;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextField txt_Ocupacion;
    public javax.swing.JTextField txt_Salario;
    public javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
