/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import net.controlador.ControladorCliente;

/**
 *
 * @author user
 */
public class VistaVisitaCliente extends javax.swing.JFrame {
    private ControladorCliente controladorCliente;
    
    /**
     * Creates new form VistaVisitaCliente
     */
    public VistaVisitaCliente(ControladorCliente controladorCliente) {
        this.controladorCliente = controladorCliente;
        initComponents();
        
        // Configura la operación de cierre de la ventana
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                controladorCliente.CerrarVistaVisita();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_visita = new javax.swing.JLabel();
        lbl_FechaVisita = new javax.swing.JLabel();
        txt_ClienteVisita = new javax.swing.JTextField();
        lbl_Placa1 = new javax.swing.JLabel();
        txt_FechaVisita = new javax.swing.JTextField();
        txt_DescripcionVisita = new javax.swing.JTextField();
        lbl_DescripcionVisita = new javax.swing.JLabel();
        btn_GuardarVisita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));

        lbl_visita.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_visita.setForeground(new java.awt.Color(255, 255, 255));
        lbl_visita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_visita.setText("VISITA");
        lbl_visita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_FechaVisita.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_FechaVisita.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FechaVisita.setText("Fecha:");

        txt_ClienteVisita.setBackground(new java.awt.Color(58, 80, 107));
        txt_ClienteVisita.setForeground(new java.awt.Color(255, 255, 255));
        txt_ClienteVisita.setBorder(null);
        txt_ClienteVisita.setEnabled(false);

        lbl_Placa1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Placa1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Placa1.setText("Cliente:");

        txt_FechaVisita.setBackground(new java.awt.Color(58, 80, 107));
        txt_FechaVisita.setForeground(new java.awt.Color(255, 255, 255));
        txt_FechaVisita.setBorder(null);
        txt_FechaVisita.setEnabled(false);

        txt_DescripcionVisita.setBackground(new java.awt.Color(58, 80, 107));
        txt_DescripcionVisita.setForeground(new java.awt.Color(255, 255, 255));
        txt_DescripcionVisita.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_DescripcionVisita.setBorder(null);

        lbl_DescripcionVisita.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_DescripcionVisita.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DescripcionVisita.setText("Descripcion:");

        btn_GuardarVisita.setBackground(new java.awt.Color(255, 255, 255));
        btn_GuardarVisita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_GuardarVisita.setForeground(new java.awt.Color(58, 80, 107));
        btn_GuardarVisita.setText("Guardar");
        btn_GuardarVisita.setBorder(null);
        btn_GuardarVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarVisitaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DescripcionVisita)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_DescripcionVisita)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Placa1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ClienteVisita))
                        .addComponent(lbl_visita, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_FechaVisita)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_FechaVisita))
                        .addComponent(btn_GuardarVisita, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_visita)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ClienteVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Placa1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FechaVisita)
                    .addComponent(txt_FechaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_DescripcionVisita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DescripcionVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_GuardarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lbl_visita.getAccessibleContext().setAccessibleName("lbl_visita");
        lbl_visita.getAccessibleContext().setAccessibleDescription("");
        lbl_visita.getAccessibleContext().setAccessibleParent(lbl_visita);
        lbl_FechaVisita.getAccessibleContext().setAccessibleName("lbl_FechaVisita");
        lbl_FechaVisita.getAccessibleContext().setAccessibleParent(lbl_FechaVisita);
        txt_ClienteVisita.getAccessibleContext().setAccessibleName("txt_ClienteVisita");
        txt_ClienteVisita.getAccessibleContext().setAccessibleParent(txt_ClienteVisita);
        txt_FechaVisita.getAccessibleContext().setAccessibleName("txt_FechaVisita");
        txt_FechaVisita.getAccessibleContext().setAccessibleParent(txt_FechaVisita);
        txt_DescripcionVisita.getAccessibleContext().setAccessibleName("txt_DescripcionVisita");
        txt_DescripcionVisita.getAccessibleContext().setAccessibleDescription("");
        txt_DescripcionVisita.getAccessibleContext().setAccessibleParent(txt_DescripcionVisita);
        lbl_DescripcionVisita.getAccessibleContext().setAccessibleName("lbl_DescripcionVisita");
        lbl_DescripcionVisita.getAccessibleContext().setAccessibleParent(lbl_DescripcionVisita);
        btn_GuardarVisita.getAccessibleContext().setAccessibleName("btn_GuardarVisita");
        btn_GuardarVisita.getAccessibleContext().setAccessibleDescription("");
        btn_GuardarVisita.getAccessibleContext().setAccessibleParent(btn_GuardarVisita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarVisitaMouseClicked
        controladorCliente.nuevaVisita();
    }//GEN-LAST:event_btn_GuardarVisitaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_GuardarVisita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DescripcionVisita;
    private javax.swing.JLabel lbl_FechaVisita;
    private javax.swing.JLabel lbl_Placa1;
    public javax.swing.JLabel lbl_visita;
    public javax.swing.JTextField txt_ClienteVisita;
    public javax.swing.JTextField txt_DescripcionVisita;
    public javax.swing.JTextField txt_FechaVisita;
    // End of variables declaration//GEN-END:variables
}
