/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.vista;

/**
 *
 * @author user
 */
public class VistaServicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaPersonal
     */
    public VistaServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Servicio = new javax.swing.JLabel();
        cmb_Personal = new javax.swing.JLabel();
        lbl_Apellido = new javax.swing.JLabel();
        lbl_Ocupacion = new javax.swing.JLabel();
        txt_Ocupacion = new javax.swing.JTextField();
        lbl_Salario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Servicio.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_Servicio.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Servicio.setText("SERVICIO");
        lbl_Servicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmb_Personal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmb_Personal.setForeground(new java.awt.Color(102, 153, 255));
        cmb_Personal.setText("Personal:");

        lbl_Apellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Apellido.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Apellido.setText("Placa:");

        lbl_Ocupacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Ocupacion.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Ocupacion.setText("Precio Servicio:");

        lbl_Salario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Salario.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Salario.setText("Descripcion:");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setBorder(null);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Apellido)
                                .addComponent(cmb_Personal)
                                .addComponent(lbl_Ocupacion)
                                .addComponent(txt_Ocupacion, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(lbl_Salario)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(lbl_Servicio))
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_Servicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_Personal)
                .addGap(1, 1, 1)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbl_Ocupacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lbl_Servicio.getAccessibleContext().setAccessibleName("lbl_Servicio");
        lbl_Servicio.getAccessibleContext().setAccessibleParent(lbl_Servicio);
        cmb_Personal.getAccessibleContext().setAccessibleName("cmb_Personal");
        cmb_Personal.getAccessibleContext().setAccessibleDescription("");
        cmb_Personal.getAccessibleContext().setAccessibleParent(cmb_Personal);
        lbl_Apellido.getAccessibleContext().setAccessibleName("lbl_Apellido");
        lbl_Apellido.getAccessibleContext().setAccessibleParent(lbl_Apellido);
        lbl_Ocupacion.getAccessibleContext().setAccessibleName("lbl_Ocupacion");
        lbl_Ocupacion.getAccessibleContext().setAccessibleParent(lbl_Ocupacion);
        txt_Ocupacion.getAccessibleContext().setAccessibleName("txt_Ocupacion");
        txt_Ocupacion.getAccessibleContext().setAccessibleParent(txt_Ocupacion);
        lbl_Salario.getAccessibleContext().setAccessibleName("lbl_Salario");
        lbl_Salario.getAccessibleContext().setAccessibleParent(lbl_Salario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmb_Personal;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_Apellido;
    private javax.swing.JLabel lbl_Ocupacion;
    public javax.swing.JLabel lbl_Salario;
    private javax.swing.JLabel lbl_Servicio;
    private javax.swing.JTextField txt_Ocupacion;
    // End of variables declaration//GEN-END:variables
}
