/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import net.controladores.ClienteJpaController;
import net.controladores.VistaController;
import net.modelo.Cliente;

/**
 *
 * @author user
 */
public class VistaCliente extends javax.swing.JFrame {

    private ClienteJpaController jpacontroller;
    private VistaPrincipal vistaPrincipal;
    private boolean editar;
    private Cliente cliente;

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public void setController(ClienteJpaController jpacontroller) {
        this.jpacontroller = jpacontroller;
    }

    public void setVistaPrincipal(VistaPrincipal vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
    }

    public void setEditar(boolean editar) {
        this.editar = editar;
    }
    
    /**
     * Creates new form VistaPersonal
     */
    public VistaCliente() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Personal = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        lbl_NombreRazon = new javax.swing.JLabel();
        lbl_TipoDocumento = new javax.swing.JLabel();
        lbl_NumeroDocumento = new javax.swing.JLabel();
        txt_NumeroDocumento = new javax.swing.JTextField();
        lbl_Direccion = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        lbl_Correo = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        cmb_TipoDocumento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Personal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_Personal.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Personal.setText("CLIENTE");
        lbl_Personal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_NombreRazon.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_NombreRazon.setForeground(new java.awt.Color(102, 153, 255));
        lbl_NombreRazon.setText("Nombre / Razon Social:");

        lbl_TipoDocumento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_TipoDocumento.setForeground(new java.awt.Color(102, 153, 255));
        lbl_TipoDocumento.setText("Tipo de Documento:");

        lbl_NumeroDocumento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_NumeroDocumento.setForeground(new java.awt.Color(102, 153, 255));
        lbl_NumeroDocumento.setText("Numero de Documento:");

        lbl_Direccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Direccion.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Direccion.setText("Direccion:");

        lbl_Telefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Telefono.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Telefono.setText("Telefono:");

        lbl_Correo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_Correo.setForeground(new java.awt.Color(102, 153, 255));
        lbl_Correo.setText("Correo:");

        btn_Guardar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Guardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar.setText("Guardar");
        btn_Guardar.setBorder(null);
        btn_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarMouseClicked(evt);
            }
        });

        cmb_TipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        cmb_TipoDocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmb_TipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_TipoDocumento)
                                .addComponent(lbl_NombreRazon)
                                .addComponent(lbl_NumeroDocumento)
                                .addComponent(txt_NumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Direccion)
                                .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Telefono)
                                .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Correo)
                                .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(lbl_Personal))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_Personal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NombreRazon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbl_TipoDocumento)
                .addGap(5, 5, 5)
                .addComponent(cmb_TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NumeroDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lbl_Personal.getAccessibleContext().setAccessibleName("lbl_Personal");
        lbl_Personal.getAccessibleContext().setAccessibleParent(lbl_Personal);
        txt_Nombre.getAccessibleContext().setAccessibleName("txt_Nombre");
        txt_Nombre.getAccessibleContext().setAccessibleParent(txt_Nombre);
        lbl_NombreRazon.getAccessibleContext().setAccessibleName("lbl_NombreRazon");
        lbl_NombreRazon.getAccessibleContext().setAccessibleDescription("");
        lbl_NombreRazon.getAccessibleContext().setAccessibleParent(lbl_NombreRazon);
        lbl_TipoDocumento.getAccessibleContext().setAccessibleName("lbl_TipoDocumento");
        lbl_TipoDocumento.getAccessibleContext().setAccessibleParent(lbl_TipoDocumento);
        lbl_NumeroDocumento.getAccessibleContext().setAccessibleName("lbl_NumeroDocumento");
        lbl_NumeroDocumento.getAccessibleContext().setAccessibleParent(lbl_NumeroDocumento);
        txt_NumeroDocumento.getAccessibleContext().setAccessibleName("txt_NumeroDocumento");
        txt_NumeroDocumento.getAccessibleContext().setAccessibleParent(txt_NumeroDocumento);
        lbl_Direccion.getAccessibleContext().setAccessibleName("lbl_Direccion");
        lbl_Direccion.getAccessibleContext().setAccessibleParent(lbl_Direccion);
        lbl_Telefono.getAccessibleContext().setAccessibleName("lbl_Telefono");
        lbl_Telefono.getAccessibleContext().setAccessibleParent(lbl_Telefono);
        lbl_Correo.getAccessibleContext().setAccessibleName("lbl_Correo");
        lbl_Correo.getAccessibleContext().setAccessibleParent(lbl_Correo);
        txt_Direccion.getAccessibleContext().setAccessibleName("txt_Direccion");
        txt_Direccion.getAccessibleContext().setAccessibleParent(txt_Direccion);
        txt_Telefono.getAccessibleContext().setAccessibleName("txt_Telefono");
        txt_Telefono.getAccessibleContext().setAccessibleDescription("");
        txt_Telefono.getAccessibleContext().setAccessibleParent(txt_Telefono);
        txt_Correo.getAccessibleContext().setAccessibleName("txt_Correo");
        txt_Correo.getAccessibleContext().setAccessibleParent(txt_Correo);
        btn_Guardar.getAccessibleContext().setAccessibleName("btn_Guardar");
        btn_Guardar.getAccessibleContext().setAccessibleDescription("");
        btn_Guardar.getAccessibleContext().setAccessibleParent(btn_Guardar);
        cmb_TipoDocumento.getAccessibleContext().setAccessibleName("cmb_TipoDocumento");
        cmb_TipoDocumento.getAccessibleContext().setAccessibleDescription("");
        cmb_TipoDocumento.getAccessibleContext().setAccessibleParent(cmb_TipoDocumento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarMouseClicked
        String nombreRazonSocial = this.txt_Nombre.getText();
        String tipoDocumento = (String) this.cmb_TipoDocumento.getSelectedItem();
        String numeroDocumento = this.txt_NumeroDocumento.getText();
        String direccionCliente = this.txt_Direccion.getText();
        String telefonoCliente = this.txt_Telefono.getText();
        String correoCliente = this.txt_Correo.getText();
        
        cliente.setNombreRazonSocial(nombreRazonSocial);
        cliente.setTipoDocumento(tipoDocumento);
        cliente.setNumeroDocumento(numeroDocumento);
        cliente.setDireccionCliente(direccionCliente);
        cliente.setTelefonoCliente(telefonoCliente);
        cliente.setCorreoCliente(correoCliente);
        
        if (editar) {
            boolean rs = false;
            try {
                rs = jpacontroller.edit(cliente);
            } catch (Exception ex) {
                Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (rs) {
                vistaPrincipal.lbl_alert.setText("Cliente Actualizado");
            } else {
                vistaPrincipal.lbl_alert.setText("Error al Actualizar Cliente");
            }
            this.dispose();
        } else {

            cliente = new Cliente(nombreRazonSocial, tipoDocumento, numeroDocumento, telefonoCliente, correoCliente, direccionCliente);
            boolean rs = jpacontroller.create(cliente);

            if (rs) {
                vistaPrincipal.lbl_alert.setText("Cliente Creado");
            } else {
                vistaPrincipal.lbl_alert.setText("Error al Crear Cliente");
            }

            this.dispose();
        }
    }//GEN-LAST:event_btn_GuardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Guardar;
    public javax.swing.JComboBox<String> cmb_TipoDocumento;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_Correo;
    public javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_NombreRazon;
    public javax.swing.JLabel lbl_NumeroDocumento;
    private javax.swing.JLabel lbl_Personal;
    public javax.swing.JLabel lbl_Telefono;
    private javax.swing.JLabel lbl_TipoDocumento;
    public javax.swing.JTextField txt_Correo;
    public javax.swing.JTextField txt_Direccion;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextField txt_NumeroDocumento;
    public javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
