/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import net.controlador.exceptions.NonexistentEntityException;
import net.controladores.VistaController;

/**
 *
 * @author user
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaController vistaController;
    
    public void setVistaController(VistaController vistaController) {
        this.vistaController = vistaController;
    }
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRepuesto = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_alert = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_cliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnHistorialCliente = new javax.swing.JButton();
        pnl_personal = new javax.swing.JPanel();
        Jtable = new javax.swing.JScrollPane();
        jTablePersonal = new javax.swing.JTable();
        btnNuevoPersonal = new javax.swing.JButton();
        btnEditarPersonal = new javax.swing.JButton();
        btnEliminarPersonal = new javax.swing.JButton();
        pnl_vehiculos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVehiculo = new javax.swing.JTable();
        pnl_repuestos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRepuesto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        btnRepuesto.setBackground(new java.awt.Color(102, 153, 255));
        btnRepuesto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnRepuesto.setText("Repuestos/Herramientas");
        btnRepuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRepuestoMouseClicked(evt);
            }
        });

        btnVehiculos.setBackground(new java.awt.Color(102, 153, 255));
        btnVehiculos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setText("Vehiculos");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
        });

        btnPersonal.setBackground(new java.awt.Color(102, 153, 255));
        btnPersonal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonal.setText("Personal");
        btnPersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(102, 153, 255));
        btnClientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("P O W E R");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("M E C H");

        lbl_alert.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_alert.setForeground(new java.awt.Color(255, 255, 255));
        lbl_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1)
                    .addComponent(btnRepuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(btnVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        btnRepuesto.getAccessibleContext().setAccessibleName("btnRepuesto");
        btnRepuesto.getAccessibleContext().setAccessibleParent(btnRepuesto);
        btnVehiculos.getAccessibleContext().setAccessibleName("btnVehiculos");
        btnVehiculos.getAccessibleContext().setAccessibleParent(btnVehiculos);
        btnPersonal.getAccessibleContext().setAccessibleName("btnPersonal");
        btnPersonal.getAccessibleContext().setAccessibleParent(btnPersonal);
        btnClientes.getAccessibleContext().setAccessibleName("btnClientes");
        btnClientes.getAccessibleContext().setAccessibleParent(btnClientes);
        jLabel2.getAccessibleContext().setAccessibleDescription("");
        lbl_alert.getAccessibleContext().setAccessibleName("lbl_alert");
        lbl_alert.getAccessibleContext().setAccessibleParent(lbl_alert);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 510));

        pnl_cliente.setBackground(new java.awt.Color(255, 255, 255));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre/Razon Social", "Tipo de Documento", "Numero de Documento", "Telefono", "Correo", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableCliente);
        jTableCliente.getAccessibleContext().setAccessibleName("jTableCliente");
        jTableCliente.getAccessibleContext().setAccessibleParent(jTableCliente);

        btnNuevoCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setForeground(new java.awt.Color(102, 153, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        btnNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoClienteMouseClicked(evt);
            }
        });

        btnEditarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setForeground(new java.awt.Color(102, 153, 255));
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        btnEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseClicked(evt);
            }
        });

        btnEliminarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setForeground(new java.awt.Color(102, 153, 255));
        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        btnEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarClienteMouseClicked(evt);
            }
        });

        btnHistorialCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialCliente.setForeground(new java.awt.Color(102, 153, 255));
        btnHistorialCliente.setText("Historial Cliente");
        btnHistorialCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        btnHistorialCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_clienteLayout = new javax.swing.GroupLayout(pnl_cliente);
        pnl_cliente.setLayout(pnl_clienteLayout);
        pnl_clienteLayout.setHorizontalGroup(
            pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addGroup(pnl_clienteLayout.createSequentialGroup()
                        .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistorialCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_clienteLayout.setVerticalGroup(
            pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorialCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNuevoCliente.getAccessibleContext().setAccessibleName("btnNuevoCliente");
        btnNuevoCliente.getAccessibleContext().setAccessibleParent(btnNuevoCliente);
        btnEditarCliente.getAccessibleContext().setAccessibleName("btnEditarCliente");
        btnEditarCliente.getAccessibleContext().setAccessibleDescription("");
        btnEditarCliente.getAccessibleContext().setAccessibleParent(btnEditarCliente);
        btnEliminarCliente.getAccessibleContext().setAccessibleName("btnEliminarCliente");
        btnEliminarCliente.getAccessibleContext().setAccessibleParent(btnEliminarCliente);
        btnHistorialCliente.getAccessibleContext().setAccessibleName("btnHistorialCliente");
        btnHistorialCliente.getAccessibleContext().setAccessibleParent(btnHistorialCliente);

        jTabbedPane1.addTab("tab1", pnl_cliente);

        pnl_personal.setBackground(new java.awt.Color(255, 255, 255));

        jTablePersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtable.setViewportView(jTablePersonal);
        jTablePersonal.getAccessibleContext().setAccessibleName("jTablePersonal");
        jTablePersonal.getAccessibleContext().setAccessibleParent(jTablePersonal);

        btnNuevoPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoPersonal.setForeground(new java.awt.Color(102, 153, 255));
        btnNuevoPersonal.setText("Nuervo Personal");
        btnNuevoPersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        btnNuevoPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoPersonalMouseClicked(evt);
            }
        });

        btnEditarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarPersonal.setForeground(new java.awt.Color(102, 153, 255));
        btnEditarPersonal.setText("Editar Personal");
        btnEditarPersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        btnEliminarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarPersonal.setForeground(new java.awt.Color(102, 153, 255));
        btnEliminarPersonal.setText("Eliminar Personal");
        btnEliminarPersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        javax.swing.GroupLayout pnl_personalLayout = new javax.swing.GroupLayout(pnl_personal);
        pnl_personal.setLayout(pnl_personalLayout);
        pnl_personalLayout.setHorizontalGroup(
            pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtable, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addGroup(pnl_personalLayout.createSequentialGroup()
                        .addComponent(btnNuevoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_personalLayout.setVerticalGroup(
            pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_personalLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnEditarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Jtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNuevoPersonal.getAccessibleContext().setAccessibleName("btnNuevoPersonal");
        btnNuevoPersonal.getAccessibleContext().setAccessibleParent(btnNuevoPersonal);
        btnEditarPersonal.getAccessibleContext().setAccessibleName("btnEditarPersonal");
        btnEditarPersonal.getAccessibleContext().setAccessibleParent(btnEditarPersonal);
        btnEliminarPersonal.getAccessibleContext().setAccessibleName("btnEliminarPersonal");
        btnEliminarPersonal.getAccessibleContext().setAccessibleParent(btnEliminarPersonal);

        jTabbedPane1.addTab("tab2", pnl_personal);

        pnl_vehiculos.setBackground(new java.awt.Color(255, 255, 255));

        jTableVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableVehiculo);

        javax.swing.GroupLayout pnl_vehiculosLayout = new javax.swing.GroupLayout(pnl_vehiculos);
        pnl_vehiculos.setLayout(pnl_vehiculosLayout);
        pnl_vehiculosLayout.setHorizontalGroup(
            pnl_vehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_vehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_vehiculosLayout.setVerticalGroup(
            pnl_vehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_vehiculosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", pnl_vehiculos);

        pnl_repuestos.setBackground(new java.awt.Color(255, 255, 255));

        jTableRepuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableRepuesto);

        javax.swing.GroupLayout pnl_repuestosLayout = new javax.swing.GroupLayout(pnl_repuestos);
        pnl_repuestos.setLayout(pnl_repuestosLayout);
        pnl_repuestosLayout.setHorizontalGroup(
            pnl_repuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_repuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_repuestosLayout.setVerticalGroup(
            pnl_repuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_repuestosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", pnl_repuestos);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -30, 780, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoClienteMouseClicked
        vistaController.CreateClienteView();
    }//GEN-LAST:event_btnNuevoClienteMouseClicked

    private void btnEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseClicked
        vistaController.UpdateClienteView();
    }//GEN-LAST:event_btnEditarClienteMouseClicked

    private void btnEliminarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarClienteMouseClicked
        try {
            vistaController.eliminar();
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarClienteMouseClicked

    private void btnHistorialClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialClienteMouseClicked
        vistaController.historialCliente();
    }//GEN-LAST:event_btnHistorialClienteMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnVehiculosMouseClicked

    private void btnRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepuestoMouseClicked
        this.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnRepuestoMouseClicked

    private void btnNuevoPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPersonalMouseClicked
        vistaController.CreatePersonalView();
    }//GEN-LAST:event_btnNuevoPersonalMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Jtable;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnEditarCliente;
    public javax.swing.JButton btnEditarPersonal;
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnEliminarPersonal;
    public javax.swing.JButton btnHistorialCliente;
    public javax.swing.JButton btnNuevoCliente;
    public javax.swing.JButton btnNuevoPersonal;
    public javax.swing.JButton btnPersonal;
    public javax.swing.JButton btnRepuesto;
    public javax.swing.JButton btnVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTableCliente;
    public javax.swing.JTable jTablePersonal;
    private javax.swing.JTable jTableRepuesto;
    private javax.swing.JTable jTableVehiculo;
    public javax.swing.JLabel lbl_alert;
    private javax.swing.JPanel pnl_cliente;
    private javax.swing.JPanel pnl_personal;
    private javax.swing.JPanel pnl_repuestos;
    private javax.swing.JPanel pnl_vehiculos;
    // End of variables declaration//GEN-END:variables
}
